<?php
// Historique des évolutions de la GMAO, par date (la plus récente en premier, tel qu'affiché).
// Entretenu manuellement : ajouter une entrée en tête de tableau à chaque nouveau lot de
// modifications déployé (voir CLAUDE.md : "chaque nouveau lot" = un feu vert de déploiement).
// Reconstitué en 2026-09-18 à partir de l'historique Git — mais pas uniquement la branche "main"
// du dépôt principal : certains correctifs vivent uniquement sur la branche du dépôt public
// FRGAgelpam (ex. retrait de données personnelles réelles), et d'autres (ex. sécurisation des
// sauvegardes du 23/08) n'ont jamais été un commit, juste une opération faite en direct sur le
// serveur. Pour un lot futur qui touche uniquement la prod/démo sans repasser par un commit local,
// penser à ajouter la ligne ici à la main.
// Traduit en FR/EN/NL (David, 18/09/2026) : chaque item est ['fr'=>, 'en'=>, 'nl'=>] — à chaque
// nouvelle entrée, écrire les 3 langues (changelog.php se replie sur 'fr' si une langue manque).
return [
    ['date' => '2026-09-18', 'items' => [
        ['fr' => "Ajout d'une page « Journal des évolutions », visible depuis l'accueil (admin), qui liste l'historique de toutes les modifications de la GMAO par date.",
         'en' => "Added a \"Changelog\" page, visible from the home screen (admin), listing the history of every change made to the CMMS by date.",
         'nl' => "Een pagina \"Wijzigingslogboek\" toegevoegd, zichtbaar vanaf het startscherm (admin), met de geschiedenis van alle wijzigingen aan de GOB per datum."],
        ['fr' => "Mise à jour de l'aide Planning avec la présentation du nouvel affichage Jour / Semaine / Mois.",
         'en' => "Updated the Schedule help page to present the new Day / Week / Month view.",
         'nl' => "De hulppagina Planning bijgewerkt met de presentatie van de nieuwe Dag- / Week- / Maandweergave."],
        ['fr' => "Réduction de la taille des tuiles et du titre sur la page d'accueil de l'Aide, pour en voir davantage sans avoir à dézoomer.",
         'en' => "Reduced the size of the tiles and title on the Help home page, so more of them fit on screen without zooming out.",
         'nl' => "De tegels en de titel op de startpagina van Help verkleind, zodat je meer ziet zonder te hoeven uitzoomen."],
        ['fr' => "Correction des captures d'écran de l'aide Paramètres qui s'affichaient en pleine résolution, débordant du cadre de la page.",
         'en' => "Fixed the Settings help page screenshots, which were displaying at full resolution and overflowing the page frame.",
         'nl' => "De screenshots van de hulppagina Instellingen gecorrigeerd: ze werden op volledige resolutie weergegeven en liepen buiten het kader van de pagina."],
    ]],
    ['date' => '2026-09-17', 'items' => [
        ['fr' => "Ajout d'un affichage Jour / Semaine / Mois sur le Planning.",
         'en' => "Added a Day / Week / Month view to the Schedule.",
         'nl' => "Een Dag- / Week- / Maandweergave toegevoegd aan de Planning."],
        ['fr' => "Correction des avatars du Planning qui n'affichaient pas la vraie photo de profil de chacun.",
         'en' => "Fixed Schedule avatars that weren't showing each person's actual profile photo.",
         'nl' => "De avatars in de Planning gecorrigeerd: ze toonden niet ieders echte profielfoto."],
        ['fr' => "Kit d'installation public : retrait de données personnelles réelles restées dans le code (nom de l'entreprise, numéros de téléphone).",
         'en' => "Public installer kit: removed real personal data left in the code (company name, phone numbers).",
         'nl' => "Publieke installatiekit: echte persoonsgegevens die nog in de code stonden verwijderd (bedrijfsnaam, telefoonnummers)."],
        ['fr' => "Kit d'installation public : retrait du plan d'accès réel et d'une seconde image de localisation du site.",
         'en' => "Public installer kit: removed the real site access map and a second location image.",
         'nl' => "Publieke installatiekit: de echte toegangsplattegrond en een tweede locatiebeeld van de site verwijderd."],
        ['fr' => "Correction des cartes Stats Techniciens invisibles sur la démo : les données de test n'étaient plus à jour avec les dernières fonctionnalités ajoutées à l'application.",
         'en' => "Fixed the Technician Stats cards being invisible on the demo: the test data was no longer up to date with the latest features added to the application.",
         'nl' => "De onzichtbare kaarten van Technicus Statistieken op de demo gecorrigeerd: de testgegevens waren niet meer bijgewerkt met de laatste functies die aan de applicatie waren toegevoegd."],
    ]],
    ['date' => '2026-09-16', 'items' => [
        ['fr' => "Mise en place d'un suivi de version et d'une procédure de mise à jour manuelle pour les installations hors-ligne.",
         'en' => "Set up version tracking and a manual update procedure for offline installations.",
         'nl' => "Versiebeheer en een handmatige update-procedure opgezet voor offline installaties."],
        ['fr' => "Remplacement du logo générique par défaut par une icône ronde neutre.",
         'en' => "Replaced the default generic logo with a neutral round icon.",
         'nl' => "Het standaard generieke logo vervangen door een neutraal rond icoon."],
        ['fr' => "Correction du logo générique affiché à tort sur les pages d'accueil du portail et de demande de travaux.",
         'en' => "Fixed the generic logo wrongly displayed on the portal home page and the work request page.",
         'nl' => "Het generieke logo gecorrigeerd dat ten onrechte werd getoond op de startpagina van het portaal en de pagina voor het melden van werk."],
    ]],
    ['date' => '2026-09-15', 'items' => [
        ['fr' => "Ajout de la sous-traitance à la checklist Travaux Hiver et correction d'un désalignement de colonnes.",
         'en' => "Added contractor work to the Winter Tasks checklist and fixed a column misalignment.",
         'nl' => "Onderaanneming toegevoegd aan de checklist Winterwerk en een uitlijningsfout in de kolommen gecorrigeerd."],
        ['fr' => "Mise en place d'un miroir complet de la prod (code + fichiers uploadés) dans le dépôt privé, pour servir de sauvegarde.",
         'en' => "Set up a full mirror of production (code + uploaded files) in the private repository, to serve as a backup.",
         'nl' => "Een volledige spiegel van de productieomgeving (code + geüploade bestanden) opgezet in de private repository, als back-up."],
    ]],
    ['date' => '2026-09-13', 'items' => [
        ['fr' => "Kit d'installation pour de nouvelles instances de la GMAO, avec passage en marque blanche (logos et textes neutres, personnalisables).",
         'en' => "Installer kit for new instances of the CMMS, made white-label (neutral, customizable logos and text).",
         'nl' => "Installatiekit voor nieuwe GOB-omgevingen, in white-label uitvoering (neutrale, aanpasbare logo's en teksten)."],
        ['fr' => "Documentation de la personnalisation de l'identité (logo, nom) dans le guide d'installation.",
         'en' => "Documented how to customize the identity (logo, name) in the installation guide.",
         'nl' => "De aanpassing van de identiteit (logo, naam) gedocumenteerd in de installatiehandleiding."],
        ['fr' => "Ajout des prérequis techniques manquants (extensions PHP, configuration serveur) au guide d'installation.",
         'en' => "Added the missing technical prerequisites (PHP extensions, server configuration) to the installation guide.",
         'nl' => "De ontbrekende technische vereisten (PHP-extensies, serverconfiguratie) toegevoegd aan de installatiehandleiding."],
    ]],
    ['date' => '2026-09-11', 'items' => [
        ['fr' => "Correction d'un débordement horizontal et d'un défilement bloqué sur mobile dans le Préventif.",
         'en' => "Fixed a horizontal overflow and blocked scrolling on mobile in Preventive.",
         'nl' => "Een horizontale overloop en geblokkeerd scrollen op mobiel in Preventief gecorrigeerd."],
        ['fr' => "Ajustement des fenêtres modales du Préventif sur mobile.",
         'en' => "Adjusted Preventive's modal windows on mobile.",
         'nl' => "De modale vensters van Preventief op mobiel aangepast."],
        ['fr' => "Ajout d'une vue en cartes, plus lisible sur mobile, pour les tableaux du Préventif.",
         'en' => "Added a card view, easier to read on mobile, for Preventive's tables.",
         'nl' => "Een kaartweergave toegevoegd, beter leesbaar op mobiel, voor de tabellen van Preventief."],
        ['fr' => "Remplacement du terme « OT » par « BI » dans toutes les pages d'aide (FR/EN/NL).",
         'en' => "Standardized terminology in the help pages: replaced the old abbreviation \"OT\" with \"Work Order\" everywhere (FR/EN/NL).",
         'nl' => "De verouderde afkorting \"OT\" overal in de hulppagina's vervangen door \"Werkorder\" (FR/EN/NL)."],
        ['fr' => "Ajout de l'impression groupée de fiches tâche pour le tableau d'atelier, et documentation dans l'aide.",
         'en' => "Added bulk printing of task slips for the workshop board, and documented it in the help pages.",
         'nl' => "Groepsafdruk van taakfiches voor het werkplaatsbord toegevoegd, en gedocumenteerd in de hulp."],
        ['fr' => "Ajout d'une fiche tâche imprimable pour l'attribution sur le tableau d'atelier.",
         'en' => "Added a printable task slip for assigning work on the workshop board.",
         'nl' => "Een afdrukbare taakfiche toegevoegd voor toewijzing op het werkplaatsbord."],
    ]],
    ['date' => '2026-09-10', 'items' => [
        ['fr' => "Reprise des captures d'écran des pages d'aide directement depuis la démo.",
         'en' => "Re-shot the help pages' screenshots directly from the demo.",
         'nl' => "De screenshots van de hulppagina's opnieuw gemaakt, rechtstreeks vanaf de demo."],
        ['fr' => "Traduction des 14 pages d'aide en français / anglais / néerlandais.",
         'en' => "Translated all 14 help pages into French / English / Dutch.",
         'nl' => "De 14 hulppagina's vertaald naar het Frans / Engels / Nederlands."],
        ['fr' => "Suppression de l'outil de renumérotation massive des BI, qui n'était plus utilisé.",
         'en' => "Removed the bulk work-order renumbering tool, which was no longer used.",
         'nl' => "De tool voor het in bulk hernummeren van werkorders verwijderd, die niet meer werd gebruikt."],
        ['fr' => "Un BI déjà créé peut maintenant être relancé tant qu'il reste « à faire ».",
         'en' => "A work order that has already been created can now be followed up again as long as it's still \"to do\".",
         'nl' => "Een reeds aangemaakte werkorder kan nu opnieuw worden aangemaand zolang deze nog \"te doen\" staat."],
        ['fr' => "Correction de BI invisibles côté service demandeur quand ils étaient classés en Préventif.",
         'en' => "Fixed work orders being invisible to the requesting department when classified as Preventive.",
         'nl' => "Werkorders die onzichtbaar waren voor de aanvragende dienst wanneer ze als Preventief waren ingedeeld, gecorrigeerd."],
        ['fr' => "Retrait des dernières fenêtres de dialogue natives du navigateur, remplacées par les modales stylées maison.",
         'en' => "Removed the last native browser dialog boxes, replaced with the app's own styled modals.",
         'nl' => "De laatste native dialoogvensters van de browser verwijderd, vervangen door de eigen gestileerde modals."],
        ['fr' => "Ajout de l'upload d'une photo de profil par utilisateur, à la place des anciennes photos nominatives fixes.",
         'en' => "Added per-user profile photo upload, replacing the old fixed name-based photos.",
         'nl' => "Het uploaden van een profielfoto per gebruiker toegevoegd, ter vervanging van de oude vaste, op naam gebaseerde foto's."],
    ]],
    ['date' => '2026-09-09', 'items' => [
        ['fr' => "Correction de l'affichage de l'intervenant qui retombait à tort sur le déclarant.",
         'en' => "Fixed the assigned technician display, which was incorrectly falling back to the person who reported the issue.",
         'nl' => "De weergave van de uitvoerende technicus gecorrigeerd, die ten onrechte terugviel op de melder."],
        ['fr' => "Correction de boutons inaccessibles à la dernière étape de l'assistant de création de BI.",
         'en' => "Fixed buttons that were unreachable at the last step of the work order creation wizard.",
         'nl' => "Onbereikbare knoppen in de laatste stap van de wizard voor het aanmaken van een werkorder gecorrigeerd."],
        ['fr' => "Possibilité d'assigner plusieurs techniciens à la création d'un BI, et correction de la date des BI de nuit.",
         'en' => "Added the ability to assign several technicians when creating a work order, and fixed the date of night-shift work orders.",
         'nl' => "Mogelijkheid toegevoegd om meerdere technici toe te wijzen bij het aanmaken van een werkorder, en de datum van nachtdienst-werkorders gecorrigeerd."],
        ['fr' => "Restructuration de l'annuaire des entreprises extérieures et enrichissement des Stats Techniciens.",
         'en' => "Restructured the external contractors directory and enhanced Technician Stats.",
         'nl' => "De directory van externe bedrijven geherstructureerd en Technicus Statistieken uitgebreid."],
        ['fr' => "Correctifs et enrichissement du Plan de Prévention.",
         'en' => "Fixes and improvements to the Safety Plan.",
         'nl' => "Correcties en verbeteringen aan het Veiligheidsplan."],
    ]],
    ['date' => '2026-09-08', 'items' => [
        ['fr' => "Ajout de la relance de demande et enrichissement de la messagerie / clôture des OT.",
         'en' => "Added the ability to follow up on a request, and enhanced the messaging / work order closing.",
         'nl' => "Mogelijkheid toegevoegd om een aanvraag aan te manen, en de berichtenfunctie / afsluiting van werkorders uitgebreid."],
    ]],
    ['date' => '2026-09-07', 'items' => [
        ['fr' => "Correction d'une perte de saisie non enregistrée dans la fiche technique.",
         'en' => "Fixed unsaved data being lost in the technical sheet.",
         'nl' => "Verlies van niet-opgeslagen invoer in het technisch fiche gecorrigeerd."],
        ['fr' => "Mise à jour des pages d'aide concernées par le chantier de traduction et les correctifs récents.",
         'en' => "Updated the help pages affected by the translation project and recent fixes.",
         'nl' => "De hulppagina's die te maken hadden met het vertaalproject en recente correcties bijgewerkt."],
        ['fr' => "Correction d'un bug qui figeait certains libellés de statut/priorité en français malgré le changement de langue.",
         'en' => "Fixed a bug that kept some status/priority labels stuck in French despite changing the language.",
         'nl' => "Een bug gecorrigeerd waardoor sommige status-/prioriteitslabels in het Frans bleven staan ondanks het wijzigen van de taal."],
        ['fr' => "Remplacement des dernières fenêtres de dialogue natives par des modales stylées dans le Parc Machine.",
         'en' => "Replaced the last native dialog boxes with styled modals in the Machine Fleet.",
         'nl' => "De laatste native dialoogvensters vervangen door gestileerde modals in het Machinepark."],
        ['fr' => "Correction de l'accord du statut « Terminé » écrit à la clôture d'un OT.",
         'en' => "Fixed a grammar mistake in the \"Completed\" status text written when closing a work order (French-only wording issue).",
         'nl' => "Een taalfout in de status \"Voltooid\" die bij het afsluiten van een werkorder werd geschreven gecorrigeerd (kwestie specifiek voor de Franse tekst)."],
        ['fr' => "Traduction complète de la GMAO en français / anglais / néerlandais.",
         'en' => "Completed the full translation of the CMMS into French / English / Dutch.",
         'nl' => "De volledige vertaling van de GOB naar het Frans / Engels / Nederlands voltooid."],
    ]],
    ['date' => '2026-09-06', 'items' => [
        ['fr' => "Correction de l'attribution des interventions par technicien et de doublons de BI.",
         'en' => "Fixed the assignment of interventions per technician and duplicate work orders.",
         'nl' => "De toewijzing van interventies per technicus en dubbele werkorders gecorrigeerd."],
        ['fr' => "Coloration du panneau Pannes récurrentes par secteur selon le type actif.",
         'en' => "Added color coding to the Recurring Breakdowns panel by sector, based on the active type.",
         'nl' => "Het paneel Terugkerende storingen per sector ingekleurd op basis van het actieve type."],
    ]],
    ['date' => '2026-09-04', 'items' => [
        ['fr' => "Mise à jour de l'aide OT sur la visibilité côté demandeur après clôture.",
         'en' => "Updated the Work Order help page on visibility for the requester after closing.",
         'nl' => "De hulppagina Werkorder bijgewerkt over de zichtbaarheid voor de aanvrager na afsluiting."],
        ['fr' => "Mise à jour de l'aide du portail service avec les nouveautés du suivi de demande.",
         'en' => "Updated the Services Portal help page with the latest changes to request tracking.",
         'nl' => "De hulppagina van het Dienstenportaal bijgewerkt met de nieuwigheden in de opvolging van aanvragen."],
        ['fr' => "Enrichissement du suivi portail service et correction du tracker de statut des BI.",
         'en' => "Enhanced the Services Portal tracking and fixed the work order status tracker.",
         'nl' => "De opvolging in het Dienstenportaal uitgebreid en de statustracker van werkorders gecorrigeerd."],
        ['fr' => "Correction d'une échéance figée sur les règles préventives en mode fréquence.",
         'en' => "Fixed a due date getting stuck on preventive rules set to frequency mode.",
         'nl' => "Een vastgelopen vervaldatum bij preventieve regels in frequentiemodus gecorrigeerd."],
        ['fr' => "Mise à jour de l'aide Préventif et de l'aide OT avec les nouveautés du SAS de validation.",
         'en' => "Updated the Preventive and Work Order help pages with the latest changes to the validation airlock.",
         'nl' => "De hulppagina's Preventief en Werkorder bijgewerkt met de nieuwigheden van het validatiesas."],
        ['fr' => "Enrichissement du SAS de validation (photos, urgence, messages), utilisable sur mobile/tablette.",
         'en' => "Enhanced the validation airlock (photos, urgency, messages), now usable on mobile/tablet.",
         'nl' => "Het validatiesas uitgebreid (foto's, urgentie, berichten), nu bruikbaar op mobiel/tablet."],
        ['fr' => "Ajout de la génération manuelle d'une demande préventive avec assignation automatique au technicien du matin.",
         'en' => "Added manual generation of a preventive request, with automatic assignment to the morning technician.",
         'nl' => "Handmatige aanmaak van een preventieve aanvraag toegevoegd, met automatische toewijzing aan de ochtendtechnicus."],
        ['fr' => "Compression automatique des photos de BI, et confidentialité des notes de planning en dehors du planning annuel.",
         'en' => "Added automatic compression of work order photos, and made schedule notes private outside the annual schedule.",
         'nl' => "Automatische compressie van werkorderfoto's toegevoegd, en planningsnotities buiten de jaarplanning vertrouwelijk gemaakt."],
    ]],
    ['date' => '2026-09-03', 'items' => [
        ['fr' => "Documentation de la limite de taille des uploads (300 Mo) dans l'aide Parc Machine.",
         'en' => "Documented the upload size limit (300 MB) in the Machine Fleet help page.",
         'nl' => "De uploadgroottelimiet (300 MB) gedocumenteerd in de hulppagina Machinepark."],
        ['fr' => "Ajout des photos sur les BI, du comptage/clignotement des messages, et mise à jour de l'aide KPI.",
         'en' => "Added photos on work orders, a message counter/blinking indicator, and updated the KPI help page.",
         'nl' => "Foto's bij werkorders toegevoegd, een berichtenteller/knipperindicator, en de hulppagina KPI bijgewerkt."],
        ['fr' => "Ajout de la répartition curatif/préventif/chantier avec un carrousel sur la page KPI.",
         'en' => "Added a corrective/preventive/project breakdown with a carousel on the KPI page.",
         'nl' => "Een verdeling curatief/preventief/project met een carrousel toegevoegd op de KPI-pagina."],
    ]],
    ['date' => '2026-09-02', 'items' => [
        ['fr' => "Message d'erreur explicite quand un upload de document/devis dépasse la taille limite.",
         'en' => "Added a clear error message when a document/quote upload exceeds the size limit.",
         'nl' => "Een duidelijke foutmelding toegevoegd wanneer een upload van een document/offerte de groottelimiet overschrijdt."],
        ['fr' => "Remplacement des 3 dernières fenêtres de confirmation natives de Paramètres par la modale stylée maison.",
         'en' => "Replaced the last 3 native confirmation dialogs in Settings with the app's own styled modal.",
         'nl' => "De laatste 3 native bevestigingsvensters in Instellingen vervangen door de eigen gestileerde modal."],
        ['fr' => "Réservation de l'ajout/suppression de documents et devis aux admins, mise à jour de l'aide Parc Machine.",
         'en' => "Restricted adding/removing documents and quotes to admins only, and updated the Machine Fleet help page.",
         'nl' => "Het toevoegen/verwijderen van documenten en offertes voorbehouden aan admins, en de hulppagina Machinepark bijgewerkt."],
        ['fr' => "Ajout de l'onglet Devis à la fiche de vie machine et enrichissement de l'historique des BI.",
         'en' => "Added a Quotes tab to the machine record and enhanced the work order history.",
         'nl' => "Een tabblad Offertes toegevoegd aan het machinefiche en de werkordergeschiedenis uitgebreid."],
    ]],
    ['date' => '2026-08-30', 'items' => [
        ['fr' => "Ajout de la sélection multiple (rectangle + déplacement groupé) dans l'éditeur de Schéma Usine ; remplacement des icônes provisoires de l'application installable par le vrai logo.",
         'en' => "Added multiple selection (rectangle select + group move) to the Diagram editor; replaced the app's temporary installable-app icons with the real logo.",
         'nl' => "Meervoudige selectie toegevoegd (rechthoek + gegroepeerd verplaatsen) aan de Schema-editor; de tijdelijke iconen van de installeerbare app vervangen door het echte logo."],
        ['fr' => "Ajout de formes industrielles au Schéma (convoyeurs, vis sans fin, tapis, bras robotisé) avec des illustrations dégradées, et corrections d'affichage à l'agrandissement/la rotation.",
         'en' => "Added industrial shapes to the Diagram (conveyors, screw conveyor, chevron belt, robotic arm) with gradient illustrations, plus display fixes when resizing/rotating.",
         'nl' => "Industriële vormen toegevoegd aan het Schema (transportbanden, vijzeltransporteur, riffelband, robotarm) met gradiëntillustraties, plus weergavecorrecties bij het vergroten/roteren."],
        ['fr' => "Mise à jour de l'aide Parc Machine sur les catégories visuelles du schéma et la rotation de texte automatique.",
         'en' => "Updated the Machine Fleet help page on the diagram's visual categories and automatic text rotation.",
         'nl' => "De hulppagina Machinepark bijgewerkt over de visuele categorieën van het schema en de automatische tekstrotatie."],
        ['fr' => "Ajout des catégories visuelles du Schéma (couleurs, effets, panneau de propriétés complet) et retrait d'un bouton de réinitialisation jugé trop dangereux.",
         'en' => "Added visual categories to the Diagram (colors, effects, full properties panel) and removed a reset button deemed too risky.",
         'nl' => "Visuele categorieën toegevoegd aan het Schema (kleuren, effecten, volledig eigenschappenpaneel) en een resetknop verwijderd die als te risicovol werd beschouwd."],
    ]],
    ['date' => '2026-08-29', 'items' => [
        ['fr' => "Modernisation de la page Paramètres (menu latéral, présentation épurée) et affinage de l'arborescence du Parc Machine.",
         'en' => "Modernized the Settings page (side menu, cleaner layout) and refined the Machine Fleet tree view.",
         'nl' => "De pagina Instellingen gemoderniseerd (zijmenu, overzichtelijkere weergave) en de boomstructuur van het Machinepark verfijnd."],
        ['fr' => "Correction d'un retour à la ligne indésirable dans le détail du SAS de validation.",
         'en' => "Fixed an unwanted line break in the validation airlock's detail view.",
         'nl' => "Een ongewenste regelafbreking in het detail van het validatiesas gecorrigeerd."],
        ['fr' => "Ajout du matériel par défaut par type d'équipement, et refonte complète de la fiche de vie machine.",
         'en' => "Added default equipment per equipment type, and fully redesigned the machine record.",
         'nl' => "Standaardmateriaal per apparatuurtype toegevoegd, en het machinefiche volledig herwerkt."],
        ['fr' => "Correction de l'affichage du SAS de validation et de la localisation précise du rapport.",
         'en' => "Fixed the display of the validation airlock and the report's precise location.",
         'nl' => "De weergave van het validatiesas en de precieze locatie van het rapport gecorrigeerd."],
    ]],
    ['date' => '2026-08-28', 'items' => [
        ['fr' => "Ajout d'un système de matériel configurable sur la fiche technique et amélioration de l'onglet Interventions.",
         'en' => "Added a configurable equipment system to the technical sheet and improved the Interventions tab.",
         'nl' => "Een configureerbaar materiaalsysteem toegevoegd aan het technisch fiche en het tabblad Interventies verbeterd."],
        ['fr' => "Affichage du nom et de la localisation de la machine du Parc Machine dans la fiche technique.",
         'en' => "Displayed the machine's name and location from the Machine Fleet on the technical sheet.",
         'nl' => "De naam en locatie van de machine uit het Machinepark weergegeven in het technisch fiche."],
        ['fr' => "Correction du bouton Schéma pour les techniciens sur la fiche machine.",
         'en' => "Fixed the Diagram button for technicians on the machine record.",
         'nl' => "De knop Schema voor technici op het machinefiche gecorrigeerd."],
    ]],
    ['date' => '2026-08-27', 'items' => [
        ['fr' => "Ajout d'un lien vers la démo publique sur la page de connexion.",
         'en' => "Added a link to the public demo on the login page.",
         'nl' => "Een link naar de publieke demo toegevoegd op de inlogpagina."],
        ['fr' => "Mise en place d'une détection d'environnement démo, utilisée pour nettoyer automatiquement la démo publique.",
         'en' => "Set up demo environment detection, used to automatically clean up the public demo.",
         'nl' => "Detectie van de demo-omgeving opgezet, gebruikt om de publieke demo automatisch op te schonen."],
        ['fr' => "La démo publique n'affiche plus le vrai Schéma d'usine (confidentiel).",
         'en' => "The public demo no longer shows the real (confidential) plant Diagram.",
         'nl' => "De publieke demo toont niet langer het echte (vertrouwelijke) fabrieksschema."],
        ['fr' => "Réorganisation et compacité de la fenêtre du rapport d'intervention, ajout de la bascule vers le préventif hivernal.",
         'en' => "Reorganized and made the intervention report window more compact, added the toggle to winter preventive maintenance.",
         'nl' => "Het venster van het interventierapport gereorganiseerd en compacter gemaakt, de schakelaar naar winterpreventief toegevoegd."],
        ['fr' => "Correction du calcul d'avance/retard 35h dans l'aperçu en direct de la modale planning.",
         'en' => "Fixed the 35h ahead/behind calculation in the schedule modal's live preview.",
         'nl' => "De 35u-voor-/achterstandberekening in de live preview van de planningsmodal gecorrigeerd."],
        ['fr' => "Refonte visuelle de la page KPI et rééquilibrage des indicateurs pannes/technicien.",
         'en' => "Redesigned the KPI page and rebalanced the breakdown/technician indicators.",
         'nl' => "De KPI-pagina visueel herwerkt en de storing-/technicusindicatoren opnieuw in balans gebracht."],
        ['fr' => "Schéma Usine : effets de forme (ombre, relief, creux, lueur), fond en dégradé, panneau de propriétés redimensionnable.",
         'en' => "Diagram: shape effects (shadow, emboss, inset, glow), gradient background, resizable properties panel.",
         'nl' => "Schema: vormeffecten (schaduw, reliëf, verdieping, gloed), verloopachtergrond, herschaalbaar eigenschappenpaneel."],
    ]],
    ['date' => '2026-08-26', 'items' => [
        ['fr' => "Schéma Usine : texte déplaçable librement, forme « texte seul », zoom à la molette.",
         'en' => "Diagram: text can now be freely moved, added a \"text only\" shape, zoom with the scroll wheel.",
         'nl' => "Schema: tekst nu vrij verplaatsbaar, vorm \"alleen tekst\" toegevoegd, zoomen met het muiswiel."],
        ['fr' => "Amélioration du Schéma Usine (agrandissement du canevas, navigation au glisser, courbes lissées).",
         'en' => "Improved the Diagram (larger canvas, drag-to-pan navigation, smoothed curves).",
         'nl' => "Het Schema verbeterd (groter canvas, navigeren door te slepen, gladde curves)."],
        ['fr' => "Ajout du Schéma Usine interactif, avec éditeur visuel complet.",
         'en' => "Added the interactive plant Diagram, with a full visual editor.",
         'nl' => "Het interactieve fabrieksschema toegevoegd, met volledige visuele editor."],
        ['fr' => "Amélioration du confort de l'onglet Travaux Hiver du Préventif.",
         'en' => "Improved the comfort of Preventive's Winter Tasks tab.",
         'nl' => "Het gebruiksgemak van het tabblad Winterwerk van Preventief verbeterd."],
        ['fr' => "Ajout d'une colonne Usine, de zones gérables et de colonnes redimensionnables.",
         'en' => "Added a Plant column, manageable zones, and resizable columns.",
         'nl' => "Een kolom Fabriek, beheerbare zones en herschaalbare kolommen toegevoegd."],
    ]],
    ['date' => '2026-08-25', 'items' => [
        ['fr' => "Amélioration de la checklist Travaux Divers du Préventif (statut, filtres, ergonomie).",
         'en' => "Improved Preventive's Miscellaneous Tasks checklist (status, filters, ergonomics).",
         'nl' => "De checklist Diverse Werken van Preventief verbeterd (status, filters, bediening)."],
        ['fr' => "Ajout d'une checklist saisonnière au Préventif, correction du transfert depuis le SAS.",
         'en' => "Added a seasonal checklist to Preventive, fixed the transfer from the validation airlock.",
         'nl' => "Een seizoensgebonden checklist toegevoegd aan Preventief, de overdracht vanuit het validatiesas gecorrigeerd."],
        ['fr' => "Documentation du transfert d'une demande vers une règle préventive.",
         'en' => "Documented how to transfer a request into a preventive rule.",
         'nl' => "De overdracht van een aanvraag naar een preventieve regel gedocumenteerd."],
        ['fr' => "Ajout du transfert d'une demande en attente vers une règle préventive.",
         'en' => "Added the ability to transfer a pending request into a preventive rule.",
         'nl' => "Mogelijkheid toegevoegd om een aanvraag in afwachting over te dragen naar een preventieve regel."],
    ]],
    ['date' => '2026-08-24', 'items' => [
        ['fr' => "Ajout d'une vue mensuelle aérée au Planning annuel sur mobile/tablette.",
         'en' => "Added a spacious monthly view to the Annual Schedule on mobile/tablet.",
         'nl' => "Een overzichtelijke maandweergave toegevoegd aan de Jaarplanning op mobiel/tablet."],
    ]],
    ['date' => '2026-08-23', 'items' => [
        ['fr' => "Documentation du guide intelligent (détection de doublons) dans l'aide des OT.",
         'en' => "Documented the smart guide (duplicate detection) in the Work Order help page.",
         'nl' => "De slimme gids (detectie van duplicaten) gedocumenteerd in de hulppagina Werkorder."],
        ['fr' => "Ajout d'un guide intelligent, détectant les doublons, à l'assistant de création de bon d'intervention.",
         'en' => "Added a smart guide, detecting duplicates, to the work order creation wizard.",
         'nl' => "Een slimme gids toegevoegd, die duplicaten detecteert, aan de wizard voor het aanmaken van een werkorder."],
        ['fr' => "Nettoyage des dernières traces du rôle « maintenance », supprimé.",
         'en' => "Cleaned up the last traces of the removed \"maintenance\" role.",
         'nl' => "De laatste sporen van de verwijderde rol \"maintenance\" opgeruimd."],
        ['fr' => "Remplacement des listes déroulantes de localisation par des tuiles dans le Préventif.",
         'en' => "Replaced the location dropdown lists with tiles in Preventive.",
         'nl' => "De locatie-keuzelijsten vervangen door tegels in Preventief."],
        ['fr' => "Fiabilisation du calcul d'avance/retard de l'annualisation.",
         'en' => "Made the annualized hours ahead/behind calculation more reliable.",
         'nl' => "De berekening van voor-/achterstand bij jaarurenregeling betrouwbaarder gemaakt."],
        ['fr' => "Sécurisation des sauvegardes : les fichiers de sauvegarde (.bak) laissés dans les dossiers accessibles par le web (prod, démo) ont été déplacés hors de portée d'une URL — ils pouvaient auparavant être téléchargés par n'importe qui connaissant leur nom.",
         'en' => "Secured backups: backup files (.bak) left in web-accessible folders (production, demo) were moved out of reach of any URL — they could previously be downloaded by anyone who knew their filename.",
         'nl' => "Back-ups beveiligd: back-upbestanden (.bak) die in via het web toegankelijke mappen stonden (productie, demo) zijn buiten bereik van een URL geplaatst — voorheen kon iedereen die de bestandsnaam kende ze downloaden."],
    ]],
    ['date' => '2026-08-22', 'items' => [
        ['fr' => "Planning mobile : vue personnelle par technicien, agenda en cartes, et correctifs d'annualisation.",
         'en' => "Mobile Schedule: personal view per technician, card-based agenda, and annualization fixes.",
         'nl' => "Mobiele Planning: persoonlijke weergave per technicus, kaartagenda, en correcties aan de jaarurenregeling."],
        ['fr' => "Transformation de la GMAO en application installable (PWA) et refonte de l'ergonomie tablette/téléphone.",
         'en' => "Turned the CMMS into an installable app (PWA) and redesigned the tablet/phone ergonomics.",
         'nl' => "De GOB omgezet in een installeerbare app (PWA) en de bediening op tablet/telefoon herwerkt."],
    ]],
    ['date' => '2026-08-21', 'items' => [
        ['fr' => "Nettoyage du rôle « maintenance », ajout d'un bouton Créer BI sur le Parc Machine, et unification de la messagerie GMAO/Portail Services.",
         'en' => "Cleaned up the \"maintenance\" role, added a \"Create work order\" button on the Machine Fleet, and unified the CMMS/Services Portal messaging.",
         'nl' => "De rol \"maintenance\" opgeruimd, een knop \"Werkorder aanmaken\" toegevoegd op het Machinepark, en de berichtenfunctie van GOB/Dienstenportaal samengevoegd."],
        ['fr' => "Correction du fuseau horaire du préventif automatique, ajout de l'historique des BI par machine et de la localisation dans le SAS.",
         'en' => "Fixed the automatic preventive maintenance timezone, added work order history per machine and location info in the validation airlock.",
         'nl' => "De tijdzone van automatisch preventief onderhoud gecorrigeerd, de werkordergeschiedenis per machine en locatiegegevens in het validatiesas toegevoegd."],
        ['fr' => "Mise à jour de la fiche d'aide du Portail Services.",
         'en' => "Updated the Services Portal help page.",
         'nl' => "De hulppagina van het Dienstenportaal bijgewerkt."],
    ]],
    ['date' => '2026-08-20', 'items' => [
        ['fr' => "Ajout de 5 pages d'aide détaillées : Sous-traitants, Parc Machine, Utilisateurs, Paramètres, Journal d'activité.",
         'en' => "Added 5 detailed help pages: Contractors, Machine Fleet, Users, Settings, Activity Log.",
         'nl' => "5 gedetailleerde hulppagina's toegevoegd: Onderaannemers, Machinepark, Gebruikers, Instellingen, Activiteitenlogboek."],
        ['fr' => "Ajout de la page d'aide détaillée du Planning, avec captures d'écran réelles.",
         'en' => "Added the detailed Schedule help page, with real screenshots.",
         'nl' => "De gedetailleerde hulppagina Planning toegevoegd, met echte screenshots."],
        ['fr' => "Masquage des tuiles verrouillées pour les non-admins, agrandissement des titres/descriptions.",
         'en' => "Hid locked tiles for non-admins, and enlarged the titles/descriptions.",
         'nl' => "Vergrendelde tegels verborgen voor niet-admins, en de titels/beschrijvingen vergroot."],
        ['fr' => "Suppression de la page Annualisation, fusionnée dans le Planning annuel ; les techniciens peuvent gérer leur propre fractionnement.",
         'en' => "Removed the Annualization page, merged into the Annual Schedule; technicians can now manage their own leave splitting.",
         'nl' => "De pagina Jaarurenregeling verwijderd en samengevoegd met de Jaarplanning; technici kunnen nu hun eigen verlofsplitsing beheren."],
        ['fr' => "Correction du RTT (reste dû, distinct du Repos).",
         'en' => "Fixed RTT (time off in lieu) tracking, now distinct from Rest days, and still owed correctly.",
         'nl' => "RTT (compensatieverlof) gecorrigeerd (nog verschuldigd saldo), los van Rust."],
        ['fr' => "Ajout d'une case « Repos » dans le planning, distincte du RTT.",
         'en' => "Added a \"Rest\" entry to the schedule, distinct from RTT.",
         'nl' => "Een optie \"Rust\" toegevoegd aan de planning, los van RTT."],
        ['fr' => "Ajout d'une bulle d'aide « Comprendre mon avance/retard » sur le Planning annuel.",
         'en' => "Added an \"Understand my hours balance\" help bubble to the Annual Schedule.",
         'nl' => "Een hulpballon \"Mijn voor-/achterstand begrijpen\" toegevoegd aan de Jaarplanning."],
        ['fr' => "Planning annuel : postes affichés en badges plutôt qu'en case pleine couleur.",
         'en' => "Annual Schedule: shifts now shown as badges rather than a solid-color cell.",
         'nl' => "Jaarplanning: diensten nu weergegeven als badges in plaats van een egaal gekleurd vak."],
        ['fr' => "Affinage visuel des badges d'écart annuel, masqués sur un jour vide.",
         'en' => "Visually refined the annual hours-balance badges, now hidden on an empty day.",
         'nl' => "De badges voor het jaarlijkse urenverschil visueel verfijnd, verborgen op een lege dag."],
        ['fr' => "Un jour férié travaillé compte désormais comme un jour normal, badges plus lisibles.",
         'en' => "A public holiday that was worked now counts as a normal day, with more readable badges.",
         'nl' => "Een gewerkte feestdag telt nu als een gewone dag, met beter leesbare badges."],
        ['fr' => "Amélioration du repère 35h/semaine (samedi/dimanche travaillés, écarts par jour/mois).",
         'en' => "Improved the 35h/week reference (Saturday/Sunday worked, day/month breakdowns).",
         'nl' => "Het 35u/week-referentiepunt verbeterd (gewerkte zaterdag/zondag, verschillen per dag/maand)."],
        ['fr' => "Correction de la détection automatique des jours fériés (ignore astreinte/heures isolées).",
         'en' => "Fixed the automatic public-holiday detection (ignores on-call duty/isolated hours).",
         'nl' => "De automatische detectie van feestdagen gecorrigeerd (negeert wachtdienst/losse uren)."],
    ]],
    ['date' => '2026-08-19', 'items' => [
        ['fr' => "Planning : remplissage rapide sur plusieurs jours, et jours fériés français automatiques.",
         'en' => "Schedule: quick-fill across several days, and automatic French public holidays.",
         'nl' => "Planning: snel invullen over meerdere dagen, en automatische Franse feestdagen."],
        ['fr' => "Planning annuel : objectif éditable, fractionnement, semaines à 48h, alerte de plafond de congés payés.",
         'en' => "Annual Schedule: editable target, leave splitting, 48h weeks, paid-leave cap alert.",
         'nl' => "Jaarplanning: bewerkbaar doel, verlofsplitsing, 48u-weken, waarschuwing bij plafond verlofdagen."],
    ]],
    ['date' => '2026-08-18', 'items' => [
        ['fr' => "Planning : la grille tient désormais dans la fenêtre sans aucune barre de défilement.",
         'en' => "Schedule: the grid now fits the window with no scrollbar at all.",
         'nl' => "Planning: het rooster past nu in het venster zonder enige schuifbalk."],
        ['fr' => "Planning : fenêtre « Planifier » rendue scrollable, ajout des badges CP/RTT/maladie/demi-CP.",
         'en' => "Schedule: made the \"Schedule\" window scrollable, added paid-leave/RTT/sick-leave/half-day badges.",
         'nl' => "Planning: het venster \"Plannen\" scrollbaar gemaakt, badges voor verlof/RTT/ziekte/halve dag toegevoegd."],
        ['fr' => "Planning annuel : un jour férié seul n'occupe plus toute la case en violet.",
         'en' => "Annual Schedule: a public holiday on its own no longer fills the whole cell in purple.",
         'nl' => "Jaarplanning: een feestdag alleen vult niet langer het hele vak paars in."],
        ['fr' => "Planning annuel : badge « JF » en texte, accolé à l'initiale du poste plutôt qu'un simple point.",
         'en' => "Annual Schedule: \"PH\" badge shown as text next to the shift's initial, instead of a simple dot.",
         'nl' => "Jaarplanning: badge \"FD\" als tekst naast de initiaal van de dienst, in plaats van een simpel puntje."],
        ['fr' => "Planning annuel : badge rond dédié pour un jour férié travaillé.",
         'en' => "Annual Schedule: dedicated round badge for a public holiday that was worked.",
         'nl' => "Jaarplanning: aparte ronde badge voor een gewerkte feestdag."],
        ['fr' => "Planning : un jour férié peut désormais se cumuler avec un poste travaillé (matin/après-midi/nuit/journée).",
         'en' => "Schedule: a public holiday can now be combined with a worked shift (morning/afternoon/night/full day).",
         'nl' => "Planning: een feestdag kan nu worden gecombineerd met een gewerkte dienst (ochtend/middag/nacht/hele dag)."],
        ['fr' => "Correction du donut Curatif vs Préventif qui restait vide sur Stats Techniciens.",
         'en' => "Fixed the Corrective vs Preventive donut chart, which stayed empty on Technician Stats.",
         'nl' => "De donutgrafiek Curatief vs Preventief die leeg bleef op Technicus Statistieken gecorrigeerd."],
        ['fr' => "Rafraîchissement des captures d'écran des pages d'aide.",
         'en' => "Refreshed the help pages' screenshots.",
         'nl' => "De screenshots van de hulppagina's vernieuwd."],
        ['fr' => "Ajout des sections Congés/RTT/Annualisation et Planning (à venir) au portail services.",
         'en' => "Added the Leave/RTT/Annualization and Schedule (coming soon) sections to the Services Portal.",
         'nl' => "De secties Verlof/RTT/Jaarurenregeling en Planning (binnenkort) toegevoegd aan het Dienstenportaal."],
        ['fr' => "Correction du calcul d'annualisation (CP/RTT/fériés/maladie) et documentation des règles légales.",
         'en' => "Fixed the annualization calculation (paid leave/RTT/public holidays/sick leave) and documented the legal rules.",
         'nl' => "De berekening van de jaarurenregeling gecorrigeerd (verlof/RTT/feestdagen/ziekte) en de wettelijke regels gedocumenteerd."],
    ]],
    ['date' => '2026-08-17', 'items' => [
        ['fr' => "Mise en ligne de la toute première version de la GMAO.",
         'en' => "Launched the very first version of the CMMS.",
         'nl' => "De allereerste versie van de GOB online gezet."],
    ]],
];
